- name: Update APT package cache
  apt: update_cache=yes
  become: true

- name: Upgrade make dependencies
  apt: name={{ item }} state=latest
  with_items: "{{ openwisp2fw_apt_make_dependencies }}"
  become: true

# fixes issue described in https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user
- name: Install acl if acting as non-root user
  become: true
  become_user: root
  apt: name=acl state=latest
  when: ansible_user != 'root'
